package cabboking1;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class adminchangepaswrd extends javax.swing.JFrame {

    /**
     * Creates new form adminchangepaswrd
     */
    String email;
    public adminchangepaswrd(String email) {
        initComponents();
        setSize(500,700);
        setVisible(true);
        this.email = email;
        tf_email.setText(email);
        tf_email.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_oldpswrd = new javax.swing.JTextField();
        tf_newpswrd = new javax.swing.JTextField();
        tf_cnfirmpswrd = new javax.swing.JTextField();
        jsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel1.setText("Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(33, 41, 140, 20);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setText("old password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(33, 82, 110, 20);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setText("new password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(33, 120, 110, 20);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setText("confirm new password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(28, 148, 160, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(41, 196, 0, 0);
        getContentPane().add(tf_email);
        tf_email.setBounds(230, 38, 150, 20);

        tf_oldpswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_oldpswrdActionPerformed(evt);
            }
        });
        getContentPane().add(tf_oldpswrd);
        tf_oldpswrd.setBounds(230, 80, 150, 20);

        tf_newpswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_newpswrdActionPerformed(evt);
            }
        });
        getContentPane().add(tf_newpswrd);
        tf_newpswrd.setBounds(230, 120, 150, 20);

        tf_cnfirmpswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cnfirmpswrdActionPerformed(evt);
            }
        });
        getContentPane().add(tf_cnfirmpswrd);
        tf_cnfirmpswrd.setBounds(230, 158, 150, 20);

        jsubmit.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jsubmit.setText("Submit");
        jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jsubmit);
        jsubmit.setBounds(154, 234, 89, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cnfirmpswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cnfirmpswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cnfirmpswrdActionPerformed

    private void tf_oldpswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_oldpswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_oldpswrdActionPerformed

    private void tf_newpswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_newpswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_newpswrdActionPerformed

    private void jsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitActionPerformed
        
 String oldpassword=tf_oldpswrd.getText();
 String newpassword=tf_newpswrd.getText();

 String confirmpassword=tf_cnfirmpswrd.getText();
//    JOptionPane.showMessageDialog(rootPane,"all fields are required");


if(oldpassword.equals("")||newpassword.equals("") || confirmpassword.equals(""))
{
    JOptionPane.showMessageDialog(rootPane,"all fields are required");
    
}
else{
    
    if(newpassword.equals(confirmpassword)){
         try{
        HttpResponse<String>res=Unirest.get("http://localhost:8888/adminchangepaswrd")
                .queryString("email",email)
                .queryString("oldpassword",oldpassword)
                .queryString("newpassword",newpassword).asString();
        if(res.getStatus()==200){
            String ans = res.getBody();
            JOptionPane.showMessageDialog(rootPane,ans);
           
            }
        }
    catch(Exception e){
        e.printStackTrace();
    }
    }
    else {
            JOptionPane.showMessageDialog(rootPane,"New Password and confrim password must be same");

    }
    
    
   
}





// TODO add your handling code here:
    }//GEN-LAST:event_jsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminchangepaswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminchangepaswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminchangepaswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminchangepaswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new adminchangepaswrd("admin@gmail.com").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jsubmit;
    private javax.swing.JTextField tf_cnfirmpswrd;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_newpswrd;
    private javax.swing.JTextField tf_oldpswrd;
    // End of variables declaration//GEN-END:variables
}
