/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import com.swing.picker.date.DateTextField;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author acs
 */
public class BOOKING_DETAILS extends javax.swing.JFrame {

    /**
     * Creates new form BOOKING_DETAILS
     */
    
    DateTextField dt1;
    DateTextField dt2;
    
    int pricewithdriver;
    int pricewithoutdriver;
    int carid;
    
  
     String carname;String type2;String description;String brand;String petroltype;int security;String photo;    
     
     public BOOKING_DETAILS(int carid,String carname,String type2,String description,String brand,String petroltype,int pricewithdriver,int pricewithoutdriver,int security,String photo) {
        initComponents();
        setSize(1000,1000);
        setVisible(true);
        
        lbcarname.setText(carname);
        lbtype.setText(type2);
        lbphoto.setText(photo);
        rbpricewithdvr.setText("price with driver :- "+pricewithdriver);
        rbpriceoutdvr.setText("price without driver :- "+pricewithoutdriver);
        
        dt1 = new DateTextField();
        dt1.setBounds(80,330, 150, 70);
       
        dt2 = new DateTextField();
        dt2.setBounds(440, 330, 150, 70);
        
        add(dt1);
        add(dt2);
        
        this.pricewithdriver = pricewithdriver;
        this.pricewithoutdriver = pricewithoutdriver;
        this.carname=carname;
        this.type2=type2;
        this.description=description;
        this.brand=brand;
        this.petroltype=petroltype;
        this.carid = carid;
        
        this.security = security;
        
         try {
                        URL uri = new URL("http://localhost:8888/GetResource/" + photo);
                        System.out.println(uri);
                        BufferedImage im = ImageIO.read(uri);
                        BufferedImage im2 = resizephoto(im, 200, 200);
                        lbphoto.setIcon(new ImageIcon(im2));

                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
    }
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbphoto = new javax.swing.JLabel();
        lbcarname = new javax.swing.JLabel();
        lbtype = new javax.swing.JLabel();
        rbpricewithdvr = new javax.swing.JRadioButton();
        rbpriceoutdvr = new javax.swing.JRadioButton();
        lbstartdate = new javax.swing.JLabel();
        lbenddate = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lbphoto);
        lbphoto.setBounds(41, 44, 121, 119);

        lbcarname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbcarname.setText("carname");
        getContentPane().add(lbcarname);
        lbcarname.setBounds(210, 40, 152, 39);

        lbtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtype.setText("type");
        getContentPane().add(lbtype);
        lbtype.setBounds(530, 50, 152, 37);

        buttonGroup1.add(rbpricewithdvr);
        rbpricewithdvr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbpricewithdvr.setSelected(true);
        rbpricewithdvr.setText("price with driver");
        getContentPane().add(rbpricewithdvr);
        rbpricewithdvr.setBounds(280, 180, 160, 37);

        buttonGroup1.add(rbpriceoutdvr);
        rbpriceoutdvr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbpriceoutdvr.setText("price without driver");
        rbpriceoutdvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpriceoutdvrActionPerformed(evt);
            }
        });
        getContentPane().add(rbpriceoutdvr);
        rbpriceoutdvr.setBounds(490, 180, 180, 37);

        lbstartdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbstartdate.setText("start date");
        getContentPane().add(lbstartdate);
        lbstartdate.setBounds(41, 263, 184, 47);

        lbenddate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbenddate.setText("end date");
        getContentPane().add(lbenddate);
        lbenddate.setBounds(497, 263, 168, 47);

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setText("submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit);
        btnsubmit.setBounds(279, 431, 152, 53);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbpriceoutdvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpriceoutdvrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbpriceoutdvrActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        int price = 0;
        if(rbpricewithdvr.isSelected()){
            price =pricewithdriver;
        }
        
         if(rbpriceoutdvr.isSelected()){
             price = pricewithoutdriver;
            
        }
        
        
         Date d = dt1.getDate();
        
        System.out.println("---------------------------------------------------------------");
       
       Date d2 = dt2.getDate();
        
       
       long duration = d2.getTime() - d.getTime();
       long getdays = TimeUnit.MILLISECONDS.toDays(duration);
       
        System.out.println(""+duration);
        System.out.println("No of Days ....."+getdays);
         
        
        if(getdays <= 0){
            System.out.println("value in negative");
            JOptionPane.showMessageDialog(rootPane, "Enter correct Date");
        }
        else {
            System.out.println("value in positive");
            
            booking_success obj = new booking_success(carid,carname,type2,description,brand,pricewithdriver,pricewithoutdriver,security,petroltype,photo,d,d2,getdays,price);
            
        }

        
        
    
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOKING_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOKING_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOKING_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOKING_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new BOOKING_DETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbcarname;
    private javax.swing.JLabel lbenddate;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JLabel lbstartdate;
    private javax.swing.JLabel lbtype;
    private javax.swing.JRadioButton rbpriceoutdvr;
    private javax.swing.JRadioButton rbpricewithdvr;
    // End of variables declaration//GEN-END:variables

 BufferedImage resizephoto(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
}
