/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.teamdev.jxbrowser.browser.Browser;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
import com.teamdev.jxbrowser.navigation.event.NavigationStarted;
import com.teamdev.jxbrowser.view.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

/**
 *
 * @author acs
 */
public class booking_success extends javax.swing.JFrame {

    /**
     * Creates new form booking_success
     */
   
    int pricewithdriver;
    int pricewithoutdriver;
    String carname;String type2;String description;String brand;
    int security;String petroltype;String photo;
    Date d1,d2;
    long noofdays;
    int price;
    int carid;

   
    
    
    
    public booking_success(int carid,String carname,String type2,String description,String brand,int pricewithdriver,int pricewithoutdriver,int security,String petroltype,String photo,Date d,Date d2,long noofdays,int price)  {
        initComponents();
        setSize(500,500);
        setVisible(true);
        
          this.pricewithdriver = pricewithdriver;
        this.pricewithoutdriver = pricewithoutdriver;
        this.carname = carname;
        this.brand=brand;
        this.security=security;
        this.photo=photo;
        this. petroltype=petroltype;
        this.price=price;
        this.carid = carid;
        this.noofdays  = noofdays;
        this.d1 = d;
        this.d2 = d2;
        
        
        lbcarname1.setText(carname);
        lbtype1.setText(type2);
        lbprice1.setText(price+"");
        lbfrom1.setText(d.toString());
        lbto1.setText(d2.toString());
        lbdays1.setText(noofdays+"");

        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcarname = new javax.swing.JLabel();
        lbtype = new javax.swing.JLabel();
        lbprice = new javax.swing.JLabel();
        lbfrom = new javax.swing.JLabel();
        lbto = new javax.swing.JLabel();
        lbdays = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lbpicloc = new javax.swing.JLabel();
        lbmob = new javax.swing.JLabel();
        lbcarname1 = new javax.swing.JLabel();
        lbtype1 = new javax.swing.JLabel();
        lbprice1 = new javax.swing.JLabel();
        lbfrom1 = new javax.swing.JLabel();
        lbto1 = new javax.swing.JLabel();
        lbdays1 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tapicloc = new javax.swing.JTextArea();
        tfmobno = new javax.swing.JTextField();
        btnbook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbcarname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbcarname.setText("car_name");
        getContentPane().add(lbcarname);
        lbcarname.setBounds(32, 46, 105, 40);

        lbtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtype.setText("type");
        getContentPane().add(lbtype);
        lbtype.setBounds(32, 97, 105, 37);

        lbprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbprice.setText("price");
        getContentPane().add(lbprice);
        lbprice.setBounds(32, 166, 105, 33);

        lbfrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbfrom.setText("from");
        getContentPane().add(lbfrom);
        lbfrom.setBounds(32, 219, 105, 38);

        lbto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbto.setText("to");
        getContentPane().add(lbto);
        lbto.setBounds(32, 275, 105, 42);

        lbdays.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbdays.setText("no_of_days");
        getContentPane().add(lbdays);
        lbdays.setBounds(32, 363, 105, 40);

        lbname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbname.setText("name");
        getContentPane().add(lbname);
        lbname.setBounds(32, 414, 105, 36);

        lbemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbemail.setText("email");
        getContentPane().add(lbemail);
        lbemail.setBounds(24, 478, 105, 32);

        lbpicloc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbpicloc.setText("pickup_location");
        getContentPane().add(lbpicloc);
        lbpicloc.setBounds(20, 540, 120, 35);

        lbmob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbmob.setText("mobile no");
        getContentPane().add(lbmob);
        lbmob.setBounds(20, 630, 105, 36);

        lbcarname1.setText("jLabel11");
        getContentPane().add(lbcarname1);
        lbcarname1.setBounds(374, 46, 162, 40);

        lbtype1.setText("jLabel12");
        getContentPane().add(lbtype1);
        lbtype1.setBounds(374, 97, 162, 38);

        lbprice1.setText("jLabel13");
        getContentPane().add(lbprice1);
        lbprice1.setBounds(374, 164, 139, 37);

        lbfrom1.setText("jLabel14");
        getContentPane().add(lbfrom1);
        lbfrom1.setBounds(374, 219, 139, 38);

        lbto1.setText("jLabel15");
        getContentPane().add(lbto1);
        lbto1.setBounds(374, 275, 139, 42);

        lbdays1.setText("jLabel16");
        getContentPane().add(lbdays1);
        lbdays1.setBounds(374, 363, 139, 40);
        getContentPane().add(tfname);
        tfname.setBounds(361, 414, 175, 36);

        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });
        getContentPane().add(tfemail);
        tfemail.setBounds(361, 478, 175, 44);

        tapicloc.setColumns(20);
        tapicloc.setRows(5);
        jScrollPane1.setViewportView(tapicloc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 540, 166, 55);

        tfmobno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmobnoActionPerformed(evt);
            }
        });
        getContentPane().add(tfmobno);
        tfmobno.setBounds(360, 630, 190, 50);

        btnbook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbook.setText("book now");
        btnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookActionPerformed(evt);
            }
        });
        getContentPane().add(btnbook);
        btnbook.setBounds(250, 740, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed

    private void btnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookActionPerformed
      int rent =((int)noofdays*price)+security;
                          System.out.println(""+price+"...."+noofdays+"..."+rent+"..."+security);

      String name=tfname.getText();
      String email=tfemail.getText();
      String mobileno=tfmobno.getText();
      String pickuplocation=tapicloc.getText();
      
      if (name.equals("") || email.equals("") || mobileno.equals("")  || pickuplocation.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "all fields are required");

        } else{
          
          
           EngineOptions options =EngineOptions.newBuilder(HARDWARE_ACCELERATED)
                .licenseKey("1BNDHFSC1FZYOGVE1RNQS81XOEOX5QI3AM89DH7XKGCG5S1LCH2FBDYAR5OF7H9SNEHOEP").build();
        Engine engine = Engine.newInstance(options);
        Browser browser = engine.newBrowser();
         SwingUtilities.invokeLater(() -> {
             BrowserView view = BrowserView.newInstance(browser);
             JFrame frame = new JFrame("payment demo");
             frame.addWindowListener(new WindowAdapter() {
                 public void windowClosing(WindowEvent e)
                 {
                     System.out.println("engine closed");
                    engine.close();
                 }
                 });
             frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
//             int amount =12345;
             browser.navigation().on(NavigationStarted.class,event ->{
                 String url = event.url();
                 System.out.println("url:"+url);
                 if(url.contains("BookingSuccess.html"))
                 {
                     String ss = url.substring(url.indexOf("?")+1);
                     String id = ss.substring(ss.indexOf("=")+1);
                    book_now();
                     frame.dispose();
                 }
             });
             browser.navigation().loadUrl("http://amrinder.vmm.education/paymentdemo.html?amount="+rent+"&name=cab_payment&desc=Car&photo=https://images-na.ssl-images-amazon.com/images/I/661yMQIMMODL._SY606_.jpg");
             frame.add(view,BorderLayout.CENTER);
             frame.setSize(1000, 700);
             frame.setLocationRelativeTo(null);
             frame.setVisible(true);
         });
     
     
     
          
          
          
          
        
      }
        
    }//GEN-LAST:event_btnbookActionPerformed

    private void tfmobnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmobnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmobnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new booking_success().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcarname;
    private javax.swing.JLabel lbcarname1;
    private javax.swing.JLabel lbdays;
    private javax.swing.JLabel lbdays1;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbfrom;
    private javax.swing.JLabel lbfrom1;
    private javax.swing.JLabel lbmob;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbpicloc;
    private javax.swing.JLabel lbprice;
    private javax.swing.JLabel lbprice1;
    private javax.swing.JLabel lbto;
    private javax.swing.JLabel lbto1;
    private javax.swing.JLabel lbtype;
    private javax.swing.JLabel lbtype1;
    private javax.swing.JTextArea tapicloc;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfmobno;
    private javax.swing.JTextField tfname;
    // End of variables declaration//GEN-END:variables

    public void book_now(){
           int rent =((int)noofdays*price)+security;
                          System.out.println(""+price+"...."+noofdays+"..."+rent+"..."+security);

      String name=tfname.getText();
      String email=tfemail.getText();
      String mobileno=tfmobno.getText();
      String pickuplocation=tapicloc.getText();
        try {
                    HttpResponse<String> res = Unirest.get("http://localhost:8888/bookingsuccess")
                            .queryString("name", name)
                            .queryString("email", email)
                            .queryString("mobileno", mobileno)
                            .queryString("pickuplocation",pickuplocation)
                            .queryString("price_per_day",price)
                            .queryString("start",d1.toString())
                            .queryString("end",d2.toString())
                            .queryString("no_of_days",noofdays)
                            .queryString("rent",rent)
                            .queryString("security",security)
                            .queryString("carid",carid)
                            
                            
                            .asString();
                    if (res.getStatus() == 200) {
                        String ans = res.getBody();
//                        JOptionPane.showMessageDialog(rootPane, ans);

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
    }

}
