/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Hp
 */
public class CabBookingGUI extends javax.swing.JFrame {

    /**
     * Creates new form CabBookingServer
     */
      cabBookingServer obj;
    public CabBookingGUI() {
        
        initComponents();
        setVisible(true);
        setSize(700,600);
        jmainimage.setBounds(10,10,700,600);
        
         try {
             File f = new File("C:\\Users\\Hp\\Pictures\\Saved Pictures\\server.jfif");
             
             if(f.exists()){
                BufferedImage img=ImageIO.read(f);
                BufferedImage newimg=resize(img,jmainimage.getWidth(),jmainimage.getHeight());
                jmainimage.setIcon(new ImageIcon(newimg));
            
             }
             else {
                 System.out.println("not");
             }
         
         
         } catch (Exception ex) {
                ex.printStackTrace();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverbtn = new javax.swing.JButton();
        stopbtn = new javax.swing.JButton();
        jmainimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        serverbtn.setBackground(new java.awt.Color(255, 204, 204));
        serverbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serverbtn.setText("start server");
        serverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverbtnActionPerformed(evt);
            }
        });
        getContentPane().add(serverbtn);
        serverbtn.setBounds(190, 100, 170, 50);

        stopbtn.setBackground(new java.awt.Color(255, 204, 204));
        stopbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stopbtn.setText("stop server");
        stopbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtnActionPerformed(evt);
            }
        });
        getContentPane().add(stopbtn);
        stopbtn.setBounds(190, 210, 170, 45);
        getContentPane().add(jmainimage);
        jmainimage.setBounds(0, 0, 440, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverbtnActionPerformed
        try {
        obj   = new cabBookingServer(8888);
        } catch (IOException ex) {
            Logger.getLogger(CabBookingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_serverbtnActionPerformed

    private void stopbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtnActionPerformed
        
        obj.shutdown();
        
        
    }//GEN-LAST:event_stopbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CabBookingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jmainimage;
    private javax.swing.JButton serverbtn;
    private javax.swing.JButton stopbtn;
    // End of variables declaration//GEN-END:variables


    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
}
