/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

/**
 *
 * @author acs
 */
public class design extends javax.swing.JPanel {

    /**
     * Creates new form design
     */
    public design() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpic = new javax.swing.JLabel();
        lbcarname1 = new javax.swing.JLabel();
        lbdesc = new javax.swing.JLabel();
        lbpricewithdvr = new javax.swing.JLabel();
        lboutdvr = new javax.swing.JLabel();

        setLayout(null);

        jpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jpic);
        jpic.setBounds(20, 20, 160, 130);

        lbcarname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbcarname1);
        lbcarname1.setBounds(330, 40, 300, 50);

        lbdesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbdesc);
        lbdesc.setBounds(330, 130, 300, 50);

        lbpricewithdvr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbpricewithdvr);
        lbpricewithdvr.setBounds(330, 220, 300, 50);

        lboutdvr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lboutdvr);
        lboutdvr.setBounds(330, 310, 300, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jpic;
    public javax.swing.JLabel lbcarname1;
    public javax.swing.JLabel lbdesc;
    public javax.swing.JLabel lboutdvr;
    public javax.swing.JLabel lbpricewithdvr;
    // End of variables declaration//GEN-END:variables
}
