/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author acs
 */
public class managecars extends javax.swing.JFrame {
JFileChooser chooser;
    /**
     * Creates new form managecars
     */
File f;
    public managecars() {
        chooser =new JFileChooser();
        initComponents();
        setVisible(true);
        setSize(1000,1000);
        
        cbtype.removeAllItems();
        for(int i=0;i<globalclass.car_type.length;i++)  {
            cbtype.addItem(globalclass.car_type[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lbcarname = new javax.swing.JLabel();
        tfcarname = new javax.swing.JTextField();
        lbtype = new javax.swing.JLabel();
        cbtype = new javax.swing.JComboBox<>();
        lbdesc = new javax.swing.JLabel();
        tfdesc = new javax.swing.JTextField();
        lbbrand = new javax.swing.JLabel();
        tfbrand = new javax.swing.JTextField();
        lbfueltype = new javax.swing.JLabel();
        lbpricewithdvr = new javax.swing.JLabel();
        tfpricewithdvr = new javax.swing.JTextField();
        lbpricewithoutdvr = new javax.swing.JLabel();
        tfpricewithoutdvr = new javax.swing.JTextField();
        lbsecurity = new javax.swing.JLabel();
        tfsecurity = new javax.swing.JTextField();
        lbphoto = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btnbrowse = new javax.swing.JButton();
        lbphotochose = new javax.swing.JLabel();
        rbpetrol = new javax.swing.JRadioButton();
        rbdiesel = new javax.swing.JRadioButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbcarname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbcarname.setText("car name");
        getContentPane().add(lbcarname);
        lbcarname.setBounds(41, 39, 94, 30);

        tfcarname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcarnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfcarname);
        tfcarname.setBounds(299, 39, 174, 30);

        lbtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtype.setText("type");
        getContentPane().add(lbtype);
        lbtype.setBounds(41, 109, 94, 33);

        cbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbtype);
        cbtype.setBounds(299, 109, 174, 33);

        lbdesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbdesc.setText("description");
        getContentPane().add(lbdesc);
        lbdesc.setBounds(41, 182, 94, 28);
        getContentPane().add(tfdesc);
        tfdesc.setBounds(299, 182, 174, 28);

        lbbrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbbrand.setText("brand");
        getContentPane().add(lbbrand);
        lbbrand.setBounds(41, 255, 94, 27);
        getContentPane().add(tfbrand);
        tfbrand.setBounds(299, 255, 174, 27);

        lbfueltype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbfueltype.setText("fuel type");
        getContentPane().add(lbfueltype);
        lbfueltype.setBounds(41, 316, 94, 26);

        lbpricewithdvr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbpricewithdvr.setText("price with driver");
        getContentPane().add(lbpricewithdvr);
        lbpricewithdvr.setBounds(41, 370, 140, 28);
        getContentPane().add(tfpricewithdvr);
        tfpricewithdvr.setBounds(299, 370, 174, 28);

        lbpricewithoutdvr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbpricewithoutdvr.setText("price without driver");
        getContentPane().add(lbpricewithoutdvr);
        lbpricewithoutdvr.setBounds(41, 432, 150, 33);
        getContentPane().add(tfpricewithoutdvr);
        tfpricewithoutdvr.setBounds(299, 432, 174, 33);

        lbsecurity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbsecurity.setText("security");
        getContentPane().add(lbsecurity);
        lbsecurity.setBounds(41, 497, 94, 31);
        getContentPane().add(tfsecurity);
        tfsecurity.setBounds(300, 480, 174, 31);

        lbphoto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbphoto.setText("photo");
        getContentPane().add(lbphoto);
        lbphoto.setBounds(41, 565, 94, 27);

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setText("submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit);
        btnsubmit.setBounds(213, 632, 109, 39);

        btnbrowse.setText("browse");
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btnbrowse);
        btnbrowse.setBounds(460, 570, 73, 23);
        getContentPane().add(lbphotochose);
        lbphotochose.setBounds(310, 530, 90, 80);

        buttonGroup4.add(rbpetrol);
        rbpetrol.setSelected(true);
        rbpetrol.setText("petrol");
        getContentPane().add(rbpetrol);
        rbpetrol.setBounds(300, 310, 53, 23);

        buttonGroup4.add(rbdiesel);
        rbdiesel.setText("diesel");
        rbdiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdieselActionPerformed(evt);
            }
        });
        getContentPane().add(rbdiesel);
        rbdiesel.setBounds(420, 310, 51, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfcarnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcarnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcarnameActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
      
      String ans="";
      if(rbpetrol.isSelected())
      {
          
          ans="petrol";
          
      }
      else
      {
          ans="diesel";
      }
        
       
        
       String carname= tfcarname.getText();
       String type = cbtype.getSelectedItem().toString();
       String description= tfdesc.getText();
       String brand= tfbrand.getText();
       String pricewithdriver= tfpricewithdvr.getText();
       String pricewithoutdriver= tfpricewithoutdvr.getText();
       String security=tfsecurity.getText();
      
       
        if(description.equals("") || brand.equals("")  || f == null){
           JOptionPane.showMessageDialog(rootPane, "All fields are required");
       }
       else {
           try {
           
           
           HttpResponse<String>res=Unirest.post("http://localhost:8888/managecars")
                   .queryString("carname",carname)
                   .queryString("type",type)
                    .queryString("description",description)
                    .queryString("brand",brand)
                    .queryString("price with driver",pricewithdriver)
                    .queryString("price without driver",pricewithoutdriver)        
                    .queryString("security",security)
                   .queryString("petroltype",ans)
                   .field("photo", f)
                    .asString();
                    
           
           if(res.getStatus() == 200){
               String anss = res.getBody(); 
               JOptionPane.showMessageDialog(rootPane, anss);
               if(anss.equals("success")){
                   managecars obj=new managecars();
               }
               
           }
           
           }
           catch(Exception e){
               e.printStackTrace();
           }
       }        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void rbdieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdieselActionPerformed

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
      int r=chooser.showOpenDialog(this);
      if(r==JFileChooser.APPROVE_OPTION)
      {
         f =chooser.getSelectedFile();
          System.out.println(f.getPath());
          try {
                BufferedImage img=ImageIO.read(f);
                BufferedImage newimg=resize(img,lbphotochose.getWidth(),lbphotochose.getHeight());
                lbphotochose.setIcon(new ImageIcon(newimg));
            } catch (Exception ex) {
                ex.printStackTrace();
            }

      }
    }//GEN-LAST:event_btnbrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managecars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managecars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managecars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managecars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managecars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbrowse;
    private javax.swing.JButton btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbtype;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lbbrand;
    private javax.swing.JLabel lbcarname;
    private javax.swing.JLabel lbdesc;
    private javax.swing.JLabel lbfueltype;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JLabel lbphotochose;
    private javax.swing.JLabel lbpricewithdvr;
    private javax.swing.JLabel lbpricewithoutdvr;
    private javax.swing.JLabel lbsecurity;
    private javax.swing.JLabel lbtype;
    private javax.swing.JRadioButton rbdiesel;
    private javax.swing.JRadioButton rbpetrol;
    private javax.swing.JTextField tfbrand;
    private javax.swing.JTextField tfcarname;
    private javax.swing.JTextField tfdesc;
    private javax.swing.JTextField tfpricewithdvr;
    private javax.swing.JTextField tfpricewithoutdvr;
    private javax.swing.JTextField tfsecurity;
    // End of variables declaration//GEN-END:variables
BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

}
