/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author acs
 */
public class MyBookings extends javax.swing.JFrame {

    /**
     * Creates new form MyBookings
     */
    ArrayList<car_booking_details> al = new  ArrayList<>();
    TableModel tm=new TableModel();
    public MyBookings() {
        initComponents();
        setSize(500, 500);
        setVisible(true);
        fetch_bookings();
        jTable1.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 210, 452, 290);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("My Bookings");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 40, 360, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void fetch_bookings(){
         try{
      
        
        HttpResponse<String> httpResponse = Unirest.get("http://localhost:8888/view")
               
                .asString();
        
        if(httpResponse.getStatus()==200)   {
                        
               String anss =httpResponse.getBody(); 
               System.out.println(""+anss);
               
               StringTokenizer st = new StringTokenizer(anss , "~~");
               al.clear();
               while(st.hasMoreTokens()){
                   String res = st.nextToken();
                   
                   
                   StringTokenizer st2 = new StringTokenizer(res,";;");

           String name  = st2.nextToken();
           String email  = st2.nextToken();
           String mobile_no  = st2.nextToken();
           String address  = st2.nextToken();
           int price_per_day  = Integer.parseInt(st2.nextToken());
           String start_date  = st2.nextToken();
           String end_date  = st2.nextToken();
           int no_of_days  =Integer.parseInt(st2.nextToken());
           int rent  = Integer.parseInt(st2.nextToken());
           int security  = Integer.parseInt(st2.nextToken());
           int car_id  = Integer.parseInt(st2.nextToken());
           String book_time  = st2.nextToken();
           String status  = st2.nextToken();
                      int booking_id  = Integer.parseInt(st2.nextToken());

                   car_booking_details obj = new car_booking_details(name, email, mobile_no, address, price_per_day, start_date, end_date, no_of_days, rent, security, car_id, book_time, status, booking_id);
            
            al.add(obj);
            
                   
               }
               
               
              tm.fireTableDataChanged();
               
               
        }
        
       }    catch(UnirestException ex){
       ex.printStackTrace();
    }
    }


class TableModel extends AbstractTableModel
        
{
    String name[]={"name","address","carid","rent"};
    public int getColumnCount()
    {
        return name.length;
}
    public int getRowCount()
            
    {
        return al.size();
    }
    public String getColumnName(int column)
    {
        return name[column];
    }
    public Object getValueAt(int rowIndex,int columnIndex)  {
        if(columnIndex==0){
            return al.get(rowIndex).name;
        }
        else if(columnIndex==1)  {
            return al.get(rowIndex).address;
        }
        else if(columnIndex==2)  {
            return al.get(rowIndex).car_id;
        }
         else if(columnIndex==3)  {
            return al.get(rowIndex).rent;
        }
        else  {
            return al.get(rowIndex).rent;
    }

}
}

}

   
   
 
            
