package cabboking1;

import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acs
 */
public class PannelDemos extends javax.swing.JFrame {

    /**
     * Creates new form PannelDemos
     */
    int x = 10,y = 10;
        int width,height;

    public PannelDemos() {
        initComponents();
        setSize(1000, 1000);
        setVisible(true);
        
        design d[] = new design[globalclass.car_type.length];
        mainpannel.setPreferredSize(new Dimension(1000, (200*globalclass.car_type.length)));
         Dimension  d1 = Toolkit.getDefaultToolkit().getScreenSize();
        
        height = d1.height;
        width = d1.width;
        
        jScrollPane1.setBounds(10,10,width,height);
        for (int i = 0; i < globalclass.car_type.length; i++) {
            d[i]  = new design();
            
            
            d[i].setBounds(x, y, 600, 200);
            
            y = y+220;
            d[i].lbcarname1.setText(globalclass.car_type[i]);
            
            mainpannel.add(d[i]);
            mainpannel.repaint();
            repaint();
            
            
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainpannel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainpannel.setBackground(new java.awt.Color(0, 102, 204));
        mainpannel.setLayout(null);
        jScrollPane1.setViewportView(mainpannel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 1060, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PannelDemos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PannelDemos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PannelDemos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PannelDemos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PannelDemos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpannel;
    // End of variables declaration//GEN-END:variables
}
