/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/**
 *
 * @author acs
 */
public class usersignup extends javax.swing.JFrame {

    /**
     * Creates new form usersignup
     */
    public usersignup() {
        initComponents();
        setVisible(true);
        setSize(900,900);
        
        cbqsn.removeAllItems();
        for(int i=0;i<globalclass.sec_ques.length;i++){
            cbqsn.addItem(globalclass.sec_ques[i]);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbsignup = new javax.swing.JLabel();
        lbusername = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        lbemail = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        lbphno = new javax.swing.JLabel();
        tfphno = new javax.swing.JTextField();
        lbpswrd = new javax.swing.JLabel();
        llbcnfrmpswrd = new javax.swing.JLabel();
        lbqsn = new javax.swing.JLabel();
        lbans = new javax.swing.JLabel();
        tfans = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        cbqsn = new javax.swing.JComboBox<>();
        tfpswrd = new javax.swing.JPasswordField();
        tfcnfrmpswrd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbsignup.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lbsignup.setText("sign up");
        getContentPane().add(lbsignup);
        lbsignup.setBounds(211, 30, 84, 35);

        lbusername.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lbusername.setText("username");
        getContentPane().add(lbusername);
        lbusername.setBounds(38, 91, 106, 38);
        getContentPane().add(tfusername);
        tfusername.setBounds(250, 89, 230, 40);

        lbemail.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lbemail.setText("Email");
        getContentPane().add(lbemail);
        lbemail.setBounds(38, 163, 106, 38);
        getContentPane().add(tfemail);
        tfemail.setBounds(250, 161, 230, 40);

        lbphno.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lbphno.setText("Phone no");
        getContentPane().add(lbphno);
        lbphno.setBounds(38, 250, 106, 40);
        getContentPane().add(tfphno);
        tfphno.setBounds(250, 260, 230, 40);

        lbpswrd.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lbpswrd.setText("Password");
        getContentPane().add(lbpswrd);
        lbpswrd.setBounds(38, 339, 106, 39);

        llbcnfrmpswrd.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        llbcnfrmpswrd.setText("Confirm Password");
        getContentPane().add(llbcnfrmpswrd);
        llbcnfrmpswrd.setBounds(38, 415, 130, 40);

        lbqsn.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lbqsn.setText("Security question");
        getContentPane().add(lbqsn);
        lbqsn.setBounds(38, 502, 120, 40);

        lbans.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lbans.setText("Security ans");
        getContentPane().add(lbans);
        lbans.setBounds(38, 576, 106, 40);

        tfans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfansActionPerformed(evt);
            }
        });
        getContentPane().add(tfans);
        tfans.setBounds(250, 580, 230, 40);

        loginbtn.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        loginbtn.setText("login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(211, 650, 125, 43);

        cbqsn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbqsn);
        cbqsn.setBounds(250, 500, 230, 50);
        getContentPane().add(tfpswrd);
        tfpswrd.setBounds(250, 330, 230, 40);

        tfcnfrmpswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcnfrmpswrdActionPerformed(evt);
            }
        });
        getContentPane().add(tfcnfrmpswrd);
        tfcnfrmpswrd.setBounds(250, 410, 230, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfansActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String username= tfusername.getText();
        String email= tfemail.getText();
        String phoneno= tfphno.getText();
        String password=tfpswrd.getText(); 
        String confirmpassword= tfcnfrmpswrd.getText();
        String securityqsn= cbqsn.getSelectedItem().toString();
        String securityans= tfans.getText();
        
        if(password.equals ("") || confirmpassword.equals("")) {
            JOptionPane.showMessageDialog(rootPane,"all fields are required");
        }
        else{
            if(password.equals(confirmpassword)) {
                try{
                 HttpResponse<String>res=Unirest.get("http://localhost:8888/usersignup")
                         .queryString("email",email)
                         .queryString("password",password)
                         .queryString("username",username)
                         .queryString("mobile no",phoneno)
                         .queryString("security question",securityqsn)
                         .queryString("security ans",securityans)
                                 .asString();
               if(res.getStatus()==200){
            String ans = res.getBody();
            JOptionPane.showMessageDialog(rootPane,ans);
           
                         }
        }
             catch(Exception e){
        e.printStackTrace();
             }
            }
            else {
                 JOptionPane.showMessageDialog(rootPane,"New Password and confrim pass must match");
           
            }
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void tfcnfrmpswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcnfrmpswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcnfrmpswrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbqsn;
    private javax.swing.JLabel lbans;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbphno;
    private javax.swing.JLabel lbpswrd;
    private javax.swing.JLabel lbqsn;
    private javax.swing.JLabel lbsignup;
    private javax.swing.JLabel lbusername;
    private javax.swing.JLabel llbcnfrmpswrd;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField tfans;
    private javax.swing.JPasswordField tfcnfrmpswrd;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfphno;
    private javax.swing.JPasswordField tfpswrd;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
