/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/**
 *
 * @author acs
 */
public class userchangepswrd extends javax.swing.JFrame {

    /**
     * Creates new form userchangepswrd
     */
    String username;
    public userchangepswrd(String username) {
        initComponents();
        setSize(700,700);
        setVisible(true);
        this.username = username;
        tfusername.setText(username);
        tfusername.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbusername = new javax.swing.JLabel();
        lboldpswd = new javax.swing.JLabel();
        lnnewpswd = new javax.swing.JLabel();
        lbcnfrmnewpswd = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        pfoldpswd = new javax.swing.JPasswordField();
        psnewpswd = new javax.swing.JPasswordField();
        pfcnfrmnewpswd = new javax.swing.JPasswordField();
        btnsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbusername.setText("username");
        getContentPane().add(lbusername);
        lbusername.setBounds(62, 51, 106, 36);

        lboldpswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lboldpswd.setText("old password");
        getContentPane().add(lboldpswd);
        lboldpswd.setBounds(62, 119, 100, 44);

        lnnewpswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lnnewpswd.setText("new password");
        getContentPane().add(lnnewpswd);
        lnnewpswd.setBounds(60, 210, 110, 37);

        lbcnfrmnewpswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbcnfrmnewpswd.setText("confirm new password");
        getContentPane().add(lbcnfrmnewpswd);
        lbcnfrmnewpswd.setBounds(60, 300, 170, 40);

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfusername);
        tfusername.setBounds(330, 60, 190, 36);
        getContentPane().add(pfoldpswd);
        pfoldpswd.setBounds(330, 130, 190, 44);

        psnewpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psnewpswdActionPerformed(evt);
            }
        });
        getContentPane().add(psnewpswd);
        psnewpswd.setBounds(330, 220, 190, 40);
        getContentPane().add(pfcnfrmnewpswd);
        pfcnfrmnewpswd.setBounds(330, 310, 190, 40);

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setText("submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit);
        btnsubmit.setBounds(270, 400, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void psnewpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psnewpswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psnewpswdActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
       String oldpassword =pfoldpswd.getText();
      String newpassword =psnewpswd.getText();
      String confirmpassword=pfcnfrmnewpswd.getText();
      
      if(oldpassword.equals("")||newpassword.equals("") || confirmpassword.equals(""))
      {
          JOptionPane.showMessageDialog(rootPane,"all fields are required");
      }
          else{
          if(newpassword.equals(confirmpassword)){
                 try{  
                     HttpResponse<String>res=Unirest.get("http://localhost:8888/changepaswrd")
                             .queryString("username",username)
                             .queryString("oldpassword",oldpassword)
                              .queryString("newpassword",newpassword).asString();
                             if(res.getStatus()==200){
                                 String ans =res.getBody();
                                 JOptionPane.showMessageDialog(rootPane,ans);
                                 
                                 }
                              
                     
                     
                     
                 }
                 
                 catch(Exception e){
                     
                   e.printStackTrace();
                         }
      }
                 else{
                         JOptionPane.showMessageDialog(rootPane,"new password and confirm password must be same");
                         }
       
    
          }
    
    
    
      
    
   
    }//GEN-LAST:event_btnsubmitActionPerformed
    
    
   
    







public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userchangepswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userchangepswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userchangepswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userchangepswrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel lbcnfrmnewpswd;
    private javax.swing.JLabel lboldpswd;
    private javax.swing.JLabel lbusername;
    private javax.swing.JLabel lnnewpswd;
    private javax.swing.JPasswordField pfcnfrmnewpswd;
    private javax.swing.JPasswordField pfoldpswd;
    private javax.swing.JPasswordField psnewpswd;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
