/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabboking1;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/**
 *
 * @author acs
 */
public class userlogin extends javax.swing.JFrame {

    /**
     * Creates new form userlogin
     */
    public userlogin() {
        initComponents();
        setVisible(true);
        setSize(500,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbusername = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        ta_password = new javax.swing.JPasswordField();
        userloginlb = new javax.swing.JLabel();
        ta_usrname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbusername.setText("username");
        getContentPane().add(lbusername);
        lbusername.setBounds(34, 57, 92, 39);

        lbpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbpassword.setText("password");
        getContentPane().add(lbpassword);
        lbpassword.setBounds(34, 156, 80, 35);

        loginbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginbtn.setText("login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(140, 260, 108, 39);

        ta_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(ta_password);
        ta_password.setBounds(144, 148, 206, 43);

        userloginlb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userloginlb.setText("user login");
        getContentPane().add(userloginlb);
        userloginlb.setBounds(154, 0, 131, 39);
        getContentPane().add(ta_usrname);
        ta_usrname.setBounds(140, 60, 210, 50);

        jButton1.setText("Not Registered yet ? Click Here to signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 380, 370, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        String username=ta_usrname.getText();
        String password=ta_password.getText();
        System.out.println(""+username+"....."+password);
        if(username.equals("") || password.equals(""))
            
        {
           JOptionPane.showMessageDialog(rootPane, "all fields are required");
        }
        else{
              try {
           
           
           HttpResponse<String>res=Unirest.get("http://localhost:8888/usercheck")
                   .queryString("username",username)
                   .queryString("password",password).asString();
           
           if(res.getStatus() == 200){
               String anss = res.getBody();
               JOptionPane.showMessageDialog(rootPane, anss);
               if(anss.equals("success")){
                   userhome obj = new userhome(username);
               }
               
           }
           
           }
           catch(Exception e){
               e.printStackTrace();
           }
       }
        
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void ta_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta_passwordActionPerformed
        
        
    }//GEN-LAST:event_ta_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        usersignup obj = new usersignup();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JLabel lbusername;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField ta_password;
    private javax.swing.JTextField ta_usrname;
    private javax.swing.JLabel userloginlb;
    // End of variables declaration//GEN-END:variables
}
